services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
    working_dir: /app
    command: sleep infinity
    stop_grace_period: 2s
    environment:
      - NODE_ENV=development
    
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - ../database/create.sql:/docker-entrypoint-initdb.d/create.sql

volumes:
  db_data: