services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    command: sleep infinity
    stop_grace_period: 2s
    depends_on:
      - postgres
    volumes:
      - ..:/app
    working_dir: /app

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - ../database/create.sql:/docker-entrypoint-initdb.d/create.sql

volumes:
  db_go_data: