FROM node:24-bookworm-slim

# Install yarn
RUN apt-get update && apt-get install -y curl gnupg git
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y yarn

WORKDIR /app

COPY node/package*.json ./
COPY node/yarn.lock ./
RUN yarn install --frozen-lockfile